name: babyv_care
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  snippet_coder_utils: ^1.0.12
  cupertino_icons: ^1.0.2
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  pinput: ^2.2.12
  cloud_firestore: ^3.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_svg: ^1.1.0

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets: 
   - assets/images/
   - assets/icons/